version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - durationcheck
    - errchkjson
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocyclo
    - gosec
    - gosmopolitan
    - govet
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - staticcheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - zerologlint
  disable:
    - exhaustive
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 2
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 160
    nakedret:
      max-func-lines: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
