on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name:   Install Linux packages
        if:     matrix.os == 'ubuntu-latest'
        run:    sudo apt update && sudo apt install -y --no-install-recommends ffmpeg

      - name:   Install Go
        uses:   actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name:   Checkout code
        uses:   actions/checkout@v2

      - name:   Test
        run:    go test -v ./...
